package test;// Generated by Selenium IDE

import model.AddressData;
import model.GroupData;
import org.junit.jupiter.api.Test;


public class AddressCreationTest extends TestBase {

  @Test
  public void canCreateAddress() {
    if (!app.groups().isGroupPresenty()){
      app.groups().createGroup(new GroupData("groups name", "group header", "group footer"));
    }
    app.address().createAddress(new AddressData("First name", "Middle name", "Last name", "Nickname"));
  }
}
